"""Field-finding F-5: worktree binary-diff apply defect (conflict_3way_failed).

Root cause: ``get_diff_vs_base`` ran ``git diff --no-color <base>`` WITHOUT
``--binary --full-index``. When a TRACKED binary file changed in the worktree
(in the field: ``__pycache__/*.pyc`` regenerated by pytest during the QA gate),
git emitted only an abbreviated ``Binary files a/… and b/… differ`` hunk with
no payload and an abbreviated index. The apply preflight
(``git apply --check --3way``) then returned rc=1 ("cannot apply binary patch
… without full index line"), surfacing as a spurious ``conflict_3way_failed``
even though the source ``.py`` hunk applied fine and main never drifted.

Two production fixes are exercised here:

* **Fix #1** — ``get_diff_vs_base`` adds ``--binary --full-index`` so a
  legitimately-tracked binary change produces a self-contained patch that
  ``apply_patch_to_main`` can land.
* **Fix #2** — generated cruft (``__pycache__/*.pyc`` and the other patterns
  in the single-source-of-truth glob set) is filtered OUT of the worktree
  diff at the diff source, so the agent never tries to deliver regenerated
  bytecode at all. A legitimately-tracked binary asset is NOT filtered.

All tests are git-only and deterministic (NO live claude).
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from orchestrator.worktree import WorktreeManager


def _init_git_repo(path: Path) -> None:
    """Initialize a minimal git repo with one commit (README only)."""
    subprocess.run(["git", "init", str(path)], check=True, capture_output=True)
    subprocess.run(
        ["git", "config", "user.email", "test@test.com"],
        cwd=str(path),
        check=True,
        capture_output=True,
    )
    subprocess.run(
        ["git", "config", "user.name", "Test"],
        cwd=str(path),
        check=True,
        capture_output=True,
    )
    (path / "README.md").write_text("# test\n")
    subprocess.run(
        ["git", "add", "."], cwd=str(path), check=True, capture_output=True
    )
    subprocess.run(
        ["git", "commit", "-m", "init"],
        cwd=str(path),
        check=True,
        capture_output=True,
    )


def _commit_all(path: Path, message: str) -> None:
    subprocess.run(
        ["git", "add", "."], cwd=str(path), check=True, capture_output=True
    )
    subprocess.run(
        ["git", "commit", "-m", message],
        cwd=str(path),
        check=True,
        capture_output=True,
    )


# Two distinct binary blobs (NUL bytes ⇒ git classifies as binary). Distinct
# so a diff is genuinely produced when the worktree swaps one for the other.
_BIN_V1 = b"\x00\x01\x02\x03BINARYv1\x00\xff\xfe"
_BIN_V2 = b"\x00\x01\x02\x03BINARYv2-CHANGED\x00\xff\xfe\x10\x20"


@pytest.mark.asyncio
async def test_tracked_binary_change_applies_via_full_index(
    tmp_path: Path,
) -> None:
    """Fix #1: a tracked NON-generated binary change applies cleanly.

    Without ``--binary --full-index`` the apply preflight raises
    WorktreeError ("cannot apply binary patch … without full index line").
    With the flag the patch is self-contained and both the source edit and
    the binary change land on main.
    """
    repo = tmp_path / "repo"
    repo.mkdir()
    _init_git_repo(repo)

    # A legitimately-tracked binary asset (NOT generated cruft) + a source
    # file, both committed so HEAD has them.
    (repo / "asset.bin").write_bytes(_BIN_V1)
    (repo / "mod.py").write_text("VALUE = 1\n")
    _commit_all(repo, "add asset + source")

    wt_dir = tmp_path / "worktrees"
    mgr = WorktreeManager(main_repo=repo, tournament_dir=wt_dir)
    wt = await mgr.create_per_task("1.1")

    # Mutate BOTH the binary asset and the source file in the worktree.
    (wt / "asset.bin").write_bytes(_BIN_V2)
    (wt / "mod.py").write_text("VALUE = 2\n")

    # The captured diff must carry a full-index binary payload.
    diff = await mgr.get_diff_vs_base(wt)
    assert "asset.bin" in diff
    assert "mod.py" in diff
    # ``--binary`` emits a GIT binary patch block; ``--full-index`` emits the
    # full (non-abbreviated) index line. Either marker proves the flag took.
    assert ("GIT binary patch" in diff) or ("literal " in diff)

    # Apply to main — this is the path that raised conflict_3way_failed.
    await mgr.apply_patch_to_main(wt, three_way=True)

    assert (repo / "asset.bin").read_bytes() == _BIN_V2
    assert (repo / "mod.py").read_text() == "VALUE = 2\n"

    await mgr.cleanup_all()


@pytest.mark.asyncio
async def test_regenerated_pyc_excluded_from_diff(tmp_path: Path) -> None:
    """Fix #2: a regenerated ``__pycache__/*.pyc`` is filtered from the diff.

    Mirrors the field defect exactly: a tracked ``.pyc`` (committed into the
    fixture by the benchmark's bare ``git add .``) gets regenerated in the
    worktree during the QA gate. The diff must EXCLUDE the ``.pyc`` and carry
    ONLY the source change, and the apply must land just the source edit.
    """
    repo = tmp_path / "repo"
    repo.mkdir()
    _init_git_repo(repo)

    pkg = repo / "pkg"
    cache = pkg / "__pycache__"
    cache.mkdir(parents=True)
    (pkg / "mod.py").write_text("VALUE = 1\n")
    (cache / "mod.cpython-311.pyc").write_bytes(_BIN_V1)
    _commit_all(repo, "add source + tracked pyc")

    wt_dir = tmp_path / "worktrees"
    mgr = WorktreeManager(main_repo=repo, tournament_dir=wt_dir)
    wt = await mgr.create_per_task("2.1")

    # Source edit (legit) + bytecode regeneration (cruft, must be dropped).
    (wt / "pkg" / "mod.py").write_text("VALUE = 2\n")
    (wt / "pkg" / "__pycache__" / "mod.cpython-311.pyc").write_bytes(_BIN_V2)

    diff = await mgr.get_diff_vs_base(wt)
    assert "pkg/mod.py" in diff
    assert ".pyc" not in diff
    assert "__pycache__" not in diff

    # Apply lands ONLY the source change; the .pyc on main is untouched.
    await mgr.apply_patch_to_main(wt, three_way=True)
    assert (repo / "pkg" / "mod.py").read_text() == "VALUE = 2\n"
    assert (
        repo / "pkg" / "__pycache__" / "mod.cpython-311.pyc"
    ).read_bytes() == _BIN_V1

    await mgr.cleanup_all()


@pytest.mark.asyncio
async def test_text_only_diff_unaffected_by_flags(tmp_path: Path) -> None:
    """Regression: ordinary text-only diffs still apply (no binary block)."""
    repo = tmp_path / "repo"
    repo.mkdir()
    _init_git_repo(repo)
    (repo / "a.py").write_text("x = 1\n")
    _commit_all(repo, "add a.py")

    wt_dir = tmp_path / "worktrees"
    mgr = WorktreeManager(main_repo=repo, tournament_dir=wt_dir)
    wt = await mgr.create_per_task("3.1")
    (wt / "a.py").write_text("x = 2\n")

    diff = await mgr.get_diff_vs_base(wt)
    assert "a.py" in diff
    assert "GIT binary patch" not in diff

    await mgr.apply_patch_to_main(wt, three_way=True)
    assert (repo / "a.py").read_text() == "x = 2\n"

    await mgr.cleanup_all()


@pytest.mark.asyncio
async def test_untracked_new_pyc_excluded_but_source_kept(
    tmp_path: Path,
) -> None:
    """Fix #2: a brand-new (untracked) ``.pyc`` is also filtered.

    The untracked-file pass in ``get_diff_vs_base`` must apply the same
    cruft filter, so a freshly-compiled ``.pyc`` that never existed at HEAD
    is dropped while an untracked source file is preserved.
    """
    repo = tmp_path / "repo"
    repo.mkdir()
    _init_git_repo(repo)

    wt_dir = tmp_path / "worktrees"
    mgr = WorktreeManager(main_repo=repo, tournament_dir=wt_dir)
    wt = await mgr.create_per_task("4.1")

    (wt / "new_src.py").write_text("created = True\n")
    cache = wt / "__pycache__"
    cache.mkdir()
    (cache / "new_src.cpython-311.pyc").write_bytes(_BIN_V1)

    diff = await mgr.get_diff_vs_base(wt)
    assert "new_src.py" in diff
    assert ".pyc" not in diff
    assert "__pycache__" not in diff

    await mgr.cleanup_all()
