"""Python symbol extractor — uses :mod:`ast` (no native deps).

Walks the parsed tree and emits one :class:`ExtractedSymbol` per top-level
``FunctionDef``, ``AsyncFunctionDef``, ``ClassDef``, and module-level
``Assign`` (constants). Methods inside classes are emitted with
``kind="method"`` and the class as a parent symbol; nested ``def``s
inside functions are skipped (low signal for the candidate digest).
"""

from __future__ import annotations

import ast

from state.language_extractors import ExtractedSymbol


_SIGNATURE_MAX_CHARS = 120


def _trim_signature(line: str) -> str:
    """Trim and bound a declaration line to fit ``signature``."""
    line = line.strip()
    if len(line) > _SIGNATURE_MAX_CHARS:
        return line[: _SIGNATURE_MAX_CHARS - 1] + "…"
    return line


class PyExtractor:
    """:class:`LanguageExtractor` for Python source files."""

    extensions: frozenset[str] = frozenset({".py"})
    lang_tag: str = "py"

    def extract(self, source: str) -> list[ExtractedSymbol]:
        """Return the top-level symbols defined in *source*.

        On :class:`SyntaxError` returns ``[]`` (best-effort; the file may
        be a partial / autogenerated stub).
        """
        try:
            tree = ast.parse(source)
        except SyntaxError:
            return []

        lines = source.splitlines()
        out: list[ExtractedSymbol] = []

        def _line(lineno: int) -> str:
            # ast linenos are 1-based.
            idx = lineno - 1
            if 0 <= idx < len(lines):
                return lines[idx]
            return ""

        for node in tree.body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                out.append(
                    ExtractedSymbol(
                        name=node.name,
                        kind="function",
                        line=node.lineno,
                        col=node.col_offset,
                        signature=_trim_signature(_line(node.lineno)),
                    )
                )
            elif isinstance(node, ast.ClassDef):
                out.append(
                    ExtractedSymbol(
                        name=node.name,
                        kind="class",
                        line=node.lineno,
                        col=node.col_offset,
                        signature=_trim_signature(_line(node.lineno)),
                    )
                )
                # Walk class body for methods.
                for child in node.body:
                    if isinstance(
                        child, (ast.FunctionDef, ast.AsyncFunctionDef)
                    ):
                        out.append(
                            ExtractedSymbol(
                                name=child.name,
                                kind="method",
                                line=child.lineno,
                                col=child.col_offset,
                                signature=_trim_signature(
                                    _line(child.lineno)
                                ),
                            )
                        )
            elif isinstance(node, ast.Assign):
                # Module-level constant / variable. One symbol per target
                # name — covers ``X = 1`` and ``X, Y = 1, 2``.
                for target in node.targets:
                    if isinstance(target, ast.Name):
                        out.append(
                            ExtractedSymbol(
                                name=target.id,
                                kind="var",
                                line=target.lineno,
                                col=target.col_offset,
                                signature=_trim_signature(
                                    _line(target.lineno)
                                ),
                            )
                        )
            elif isinstance(node, ast.AnnAssign):
                # Annotated module-level assignment ``X: int = 1``.
                if isinstance(node.target, ast.Name):
                    out.append(
                        ExtractedSymbol(
                            name=node.target.id,
                            kind="var",
                            line=node.target.lineno,
                            col=node.target.col_offset,
                            signature=_trim_signature(
                                _line(node.target.lineno)
                            ),
                        )
                    )

        return out


__all__ = ["PyExtractor"]
