"""Git utility helpers shared across platform adapters."""

from __future__ import annotations

import fnmatch
import logging
from pathlib import Path


_log = logging.getLogger(__name__)


# Bug #3 (v0.25.1): cap path length at POSIX ``NAME_MAX`` (255). Developer
# agents occasionally emit a JSON-escaped multi-line code listing into the
# ``diff`` field of ``.autodev/responses/{task_id}-{role}.json``; the entire
# 4000+ char blob then arrives as a single ``+++ b/<path>`` line. The
# downstream QA helpers' ``Path.is_file()`` then raises ``OSError [Errno 63]
# File name too long``. Sanitising at the source keeps the rest of the
# pipeline simple.
_MAX_PATH_LEN = 255

__all__ = [
    "_git_porcelain_set",
    "_diff_files",
    "_git_diff",
    "_git_diff_with_untracked",
    "_git_diff_range",
    "_git_rev_parse_head",
    "clear_stale_index_lock",
    "extract_files_from_diff",
    "GENERATED_FILE_GLOBS",
    "matches_generated_glob",
    "filter_generated_from_diff",
]


# Generated / lock files that carry no review signal AND must never be
# DELIVERED. The glob set itself dates to v0.31.0 (Phase 1.4), where it
# was introduced for the chunked-review skip; ``filter_generated_from_diff``
# (below) is new in F-5 and reuses the SAME set so the predicate stays a
# single source of truth. Two consumers share it:
#
# 1. The chunked review envelope (``orchestrator.execute_phase``) skips
#    these wholesale so the per-file budget is spent on files a human
#    reviewer would actually want to see (v0.31.0 / Phase 1.4).
# 2. F-5: ``WorktreeManager.get_diff_vs_base`` filters these OUT of the
#    delivered worktree diff. The field symptom was a tracked
#    ``__pycache__/*.pyc`` regenerated by pytest during the QA gate: git
#    emitted only an abbreviated "Binary files … differ" hunk, the apply
#    preflight rejected it ("cannot apply binary patch … without full
#    index"), and the worktree→main apply failed as a spurious
#    ``conflict_3way_failed``. The agent should never ship regenerated
#    bytecode, so it is dropped at the diff source — before any apply.
GENERATED_FILE_GLOBS: tuple[str, ...] = (
    "*.lock",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "Cargo.lock",
    "uv.lock",
    "poetry.lock",
    "Gemfile.lock",
    "composer.lock",
    "*.min.js",
    "*.min.css",
)


def matches_generated_glob(path: str) -> bool:
    """Return True if ``path`` is a generated/lock file with no edit signal.

    Matches any glob in :data:`GENERATED_FILE_GLOBS` (against both the full
    path and its basename) plus any path containing a ``__pycache__/``
    segment. CAUTION: this intentionally matches ONLY clearly-generated
    artefacts — never a legitimately-tracked source file or binary asset a
    real task targets. Callers that DELIVER a diff (not just review it) rely
    on that narrowness so they don't silently drop a task's actual changes.
    """
    base = path.rsplit("/", 1)[-1]
    for pattern in GENERATED_FILE_GLOBS:
        if fnmatch.fnmatch(path, pattern) or fnmatch.fnmatch(base, pattern):
            return True
    # Also skip any path containing a ``__pycache__/`` segment.
    return "__pycache__/" in path or path.startswith("__pycache__/")


def filter_generated_from_diff(diff: str) -> str:
    """Drop generated-file sections from a unified diff (single source set).

    Splits ``diff`` into per-file sections keyed on the ``diff --git a/<p>
    b/<p>`` header and removes any section whose target path satisfies
    :func:`matches_generated_glob`. Sections for legitimately-tracked files
    are preserved byte-for-byte. Lines preceding the first ``diff --git``
    header (rare; usually empty in captured diffs) are preserved as-is.

    Used at the worktree diff source (F-5) so every consumer of the
    delivered diff — ``get_diff_vs_base`` and the ``apply_patch_to_main``
    path — sees a diff free of regenerated cruft.
    """
    if not diff:
        return diff
    lines = diff.splitlines(keepends=True)
    out: list[str] = []
    current: list[str] | None = None
    current_drop = False
    preamble: list[str] = []
    for line in lines:
        if line.startswith("diff --git "):
            # Flush the previous section (if kept).
            if current is not None and not current_drop:
                out.extend(current)
            parts = line.strip().split()
            # ``diff --git a/foo b/foo`` — prefer the b-side (post-change)
            # path; fall back to the a-side, then a sentinel.
            target = parts[3][2:] if len(parts) >= 4 else (
                parts[2][2:] if len(parts) >= 3 else "<unknown>"
            )
            current_drop = matches_generated_glob(target)
            current = [line]
        elif current is None:
            preamble.append(line)
        else:
            current.append(line)
    if current is not None and not current_drop:
        out.extend(current)
    if not out:
        # No surviving sections; return only the (rare) preamble.
        return "".join(preamble)
    return "".join(preamble) + "".join(out)


# v0.40.0 (huge-repo Gap 3): how old an ``index.lock`` must be before we
# consider it abandoned. A live ``git`` op refreshes/holds the lock for the
# duration of the index write; on a healthy host that completes in well
# under a second, so 30 s is comfortably beyond any legitimate in-flight
# index mutation while still clearing the residue a killed ``git worktree
# add`` (timed out on a huge LFS repo) leaves behind.
_STALE_INDEX_LOCK_AGE_S = 30.0


def _pid_is_alive(pid: int) -> bool:
    """Return ``True`` if a process with *pid* currently exists.

    Uses ``os.kill(pid, 0)`` which sends no signal but raises
    :class:`ProcessLookupError` when no such process exists (and
    :class:`PermissionError` when the process exists but is owned by
    another user — still "alive" for our purposes). Any other ``OSError``
    is treated conservatively as "alive" so we never clear a lock we're
    unsure about.
    """
    import os

    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    except OSError:
        return True
    return True


def _read_lock_owner_pid(lock_path: Path) -> int | None:
    """Best-effort read of the PID written inside an ``index.lock``.

    Modern git writes the locking process's PID (and other metadata) into
    the lock file. When present and parseable we use it to check liveness
    directly. Returns ``None`` when the file is empty, unreadable, or the
    contents don't start with an integer (older git, or a partially
    written lock) — the caller then falls back to the mtime heuristic.
    """
    try:
        raw = lock_path.read_text(errors="replace").strip()
    except OSError:
        return None
    if not raw:
        return None
    first = raw.splitlines()[0].strip()
    # git's lock payload may be ``<pid> <hostname> ...``; take the leading
    # token only.
    token = first.split()[0] if first.split() else first
    try:
        pid = int(token)
    except ValueError:
        return None
    return pid if pid > 0 else None


def clear_stale_index_lock(
    git_dir: Path,
    *,
    max_age_s: float = _STALE_INDEX_LOCK_AGE_S,
) -> bool:
    """Remove a STALE ``<git_dir>/index.lock``; refuse a fresh/live one.

    v0.40.0 (huge-repo Gap 3): a ``git worktree add`` that is killed after
    timing out on a huge LFS repo can leave a stale ``index.lock`` in the
    MAIN repo's git dir. The very next main-repo index mutation (the
    ``git apply`` patch-integration step) then fails with::

        fatal: Unable to create '.../.git/index.lock': File exists.

    cascading the single timeout into every subsequent apply. This helper
    is the belt-and-suspenders cleanup: it removes the lock ONLY when it is
    safe to do so, so a genuinely concurrent git op is never disturbed.

    A lock is removed when BOTH hold:

    * No live owner — if the lock file records a PID and that process is
      still alive, we refuse (a real git op holds it). When no parseable
      PID is present we fall back to the age check alone.
    * Stale by age — the file's mtime is older than ``max_age_s`` (default
      30 s). A fresh lock (a real op mid-write) is always kept.

    Idempotent and safe to call before every main-repo index mutation:
    when no lock exists it is a no-op returning ``False``.

    Args:
        git_dir: the repository's git directory (``<repo>/.git``). The
            lock checked is ``git_dir / "index.lock"``.
        max_age_s: minimum mtime age before a PID-less lock is cleared.

    Returns:
        ``True`` if a stale lock was removed; ``False`` otherwise (no lock,
        or the lock was deemed fresh / owned by a live process).
    """
    import time

    try:
        gd = Path(git_dir)
    except TypeError:
        return False
    lock_path = gd / "index.lock"
    try:
        st = lock_path.stat()
    except (FileNotFoundError, NotADirectoryError):
        return False
    except OSError:
        return False

    # 1. Refuse if a live owner is recorded in the lock payload.
    owner_pid = _read_lock_owner_pid(lock_path)
    if owner_pid is not None and _pid_is_alive(owner_pid):
        _log.warning(
            "git.index_lock.live_owner",
            extra={"lock": str(lock_path), "pid": owner_pid},
        )
        return False

    # 2. Refuse a fresh lock regardless of recorded PID — a real op may be
    #    mid-write before stamping its PID. ``time.time`` and mtime share a
    #    clock; clamp negatives (clock skew) to "fresh" to stay safe.
    age_s = time.time() - st.st_mtime
    if age_s < max_age_s:
        return False

    try:
        lock_path.unlink()
    except FileNotFoundError:
        # Raced with another cleaner / the owning op finishing. Either way
        # the lock is gone now — treat as success-ish but report no removal
        # since we didn't do it.
        return False
    except OSError as exc:
        _log.warning(
            "git.index_lock.unlink_failed",
            extra={"lock": str(lock_path), "err": str(exc)},
        )
        return False

    _log.warning(
        "git.index_lock.stale_cleared",
        extra={"lock": str(lock_path), "age_s": round(age_s, 1)},
    )
    return True


def _git_porcelain_set(cwd: Path) -> set[str] | None:
    """Snapshot tracked+untracked filenames reported by `git status --porcelain`.

    Returns None if `cwd` is not a git repo (no `.git` dir), signalling that
    diff tracking is not possible.
    """
    try:
        cwd_path = Path(cwd)
    except TypeError:
        return None
    if not (cwd_path / ".git").exists():
        return None
    try:
        import subprocess  # local import to keep adapter core importable

        out = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=str(cwd_path),
            capture_output=True,
            text=True,
            errors="replace",
            timeout=5,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if out.returncode != 0:
        return None
    files: set[str] = set()
    for line in out.stdout.splitlines():
        # porcelain format: "XY path" (first two cols are status flags).
        if len(line) < 4:
            continue
        path = line[3:].strip()
        # Handle rename entries "old -> new".
        if " -> " in path:
            path = path.split(" -> ", 1)[1]
        files.add(path)
    return files


def _diff_files(before: set[str] | None, after: set[str] | None) -> list[str]:
    """Return filenames that appear in `after` but not in `before`.

    `git status --porcelain` shows a line per changed-or-untracked file with a
    status prefix. If a tracked file is modified during the run, it will appear
    in `after` (with a modification flag) but not in `before` (if it was clean
    before). Newly-untracked files similarly only show in `after`. A file that
    was modified before AND is still modified after shows up in both sets with
    the same status line, so we'd miss it — acceptable for Phase 2 (we care
    about work the agent just did). Phase 3+ may switch to diff-based tracking.
    """
    if before is None or after is None:
        return []
    return sorted(after - before)


def _git_diff(cwd: Path) -> str | None:
    try:
        import subprocess

        out = subprocess.run(
            ["git", "diff", "HEAD"],
            cwd=str(cwd),
            capture_output=True,
            text=True,
            errors="replace",
            timeout=10,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if out.returncode != 0:
        return None
    return out.stdout or None


def _list_untracked(cwd: Path) -> list[str]:
    """v0.22.1 A5: paths of untracked, non-gitignored files in *cwd*.

    Returns ``[]`` for non-repos / subprocess failure. Used by
    :func:`_git_diff_with_untracked` to surface new files in adapter
    evidence. Mirrors
    :meth:`orchestrator.worktree.WorktreeManager._list_untracked`.
    """
    try:
        import subprocess

        out = subprocess.run(
            ["git", "ls-files", "--others", "--exclude-standard"],
            cwd=str(cwd),
            capture_output=True,
            text=True,
            errors="replace",
            timeout=5,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return []
    if out.returncode != 0:
        return []
    return [line for line in out.stdout.splitlines() if line.strip()]


def _git_diff_with_untracked(cwd: Path) -> str | None:
    """v0.22.1 A5: ``git diff HEAD`` plus a per-untracked-file diff block.

    The legacy :func:`_git_diff` calls ``git diff HEAD`` only — that
    omits untracked files. Every developer task that creates new files
    (e.g. ``notes/foo.md``) ended up with ``evidence.diff = null``
    despite ``files_changed`` being populated (D-3 finding from the
    2026-05-09 Unity stall). This sibling helper appends per-untracked
    ``git diff --no-color --no-index /dev/null <rel>`` blocks. ``git
    diff --no-index`` returns rc=1 when files differ (the success case
    here), so we accept rc in (0, 1). Returns ``None`` outside a git
    repo or when there is genuinely nothing to diff. Mirrors
    :meth:`orchestrator.worktree.WorktreeManager.get_diff_vs_base`.
    """
    import subprocess

    cwd_path = Path(cwd)
    if not (cwd_path / ".git").exists():
        return None
    # Tracked-side diff: empty string when clean (NOT the same as no-repo).
    base = _git_diff(cwd) or ""
    diff_text = base
    for rel in _list_untracked(cwd):
        try:
            out = subprocess.run(
                ["git", "diff", "--no-color", "--no-index", "/dev/null", rel],
                cwd=str(cwd),
                capture_output=True,
                text=True,
            errors="replace",
                timeout=10,
                check=False,
            )
        except (OSError, subprocess.SubprocessError):
            continue
        if out.returncode in (0, 1):
            diff_text += out.stdout
    return diff_text or None


def _git_diff_range(cwd: Path, from_sha: str, to_sha: str) -> str | None:
    """Return the unified diff between two commits, or ``None`` on failure.

    Used by the v0.9.0 phase-review tournament to materialize the
    "as-implemented" A variant of the :class:`PhaseReviewBundle` from the
    range ``phase.baseline_commit..HEAD``. Mirrors :func:`_git_diff` error
    handling (returns ``None`` on subprocess / git failure rather than
    raising) so the caller can degrade gracefully — phase review continues
    with an empty diff rather than blocking forward progress.

    The two-dot range form ``from_sha..to_sha`` is intentional: it shows
    every commit reachable from ``to_sha`` that isn't reachable from
    ``from_sha``. With a linear history this is the same as
    ``git diff from_sha to_sha`` but treats merges sensibly.
    """
    try:
        import subprocess

        out = subprocess.run(
            ["git", "diff", f"{from_sha}..{to_sha}"],
            cwd=str(cwd),
            capture_output=True,
            text=True,
            errors="replace",
            timeout=15,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if out.returncode != 0:
        return None
    return out.stdout or None


def _sanitize_diff_path(path: str) -> str | None:
    """Return a cleaned diff path, or ``None`` if it is pathological.

    Bug #3 (v0.25.1): reject paths that are never real. A 4000-char blob
    with embedded newlines / NUL bytes (a JSON-escaped code listing that
    leaked into a ``+++ b/`` line) is not a path; the downstream QA helpers'
    ``Path.is_file()`` raises ``OSError [Errno 63] File name too long`` on
    it. Applied to BOTH the ``+++ b/`` path and the binary header-fallback
    path so the two routes share one sanitiser (F-4).
    """
    path = path.strip()
    if not path:
        return None
    reason: str | None = None
    if len(path) > _MAX_PATH_LEN:
        reason = f"len={len(path)} > {_MAX_PATH_LEN}"
    elif "\n" in path or "\\n" in path:
        reason = "embedded newline"
    elif "\x00" in path:
        reason = "embedded NUL"
    if reason is not None:
        _log.warning(
            "extract_files_from_diff.rejected_path",
            extra={
                "reason": reason,
                "path_prefix": path[:80],
            },
        )
        return None
    return path


def _section_is_binary(section: list[str]) -> bool:
    """Return ``True`` iff the section is a GENUINELY-binary diff section.

    A section qualifies only on a POSITIVE binary marker — a ``GIT binary
    patch`` payload line (``git diff --binary``) or a ``Binary files a/<x>
    and b/<y> differ`` line (``git diff`` without ``--binary``). This
    deliberately does NOT treat "a ``diff --git`` header with no ``+++ b/``"
    as binary: a header cut off before its ``+++ b/`` / hunks is a TRUNCATED
    or hallucinated text diff, which the QA-gate fail-closed contract (v0.27)
    requires to parse as "no files" — not as a binary edit. Only the explicit
    marker promotes a header-only section to the binary header fallback.
    """
    for line in section:
        if line.startswith("GIT binary patch"):
            return True
        if line.startswith("Binary files ") and line.rstrip().endswith(
            " differ"
        ):
            return True
    return False


def _binary_section_target(section: list[str]) -> str | None:
    """Resolve the post-change path of a GENUINELY-binary section.

    Precondition: :func:`_section_is_binary` is ``True`` for ``section`` —
    i.e. it carries a ``GIT binary patch`` payload or a ``Binary files ..
    differ`` line and has NO ``+++ b/`` header. F-4: fall back to the b-side
    path so binary edits are still visible to scope gating. Prefers the
    ``Binary files .. and <b> differ`` line (carries the canonical
    ``/dev/null`` deletion sentinel), then the ``diff --git a/<x> b/<y>``
    header. ``/dev/null`` targets (binary deletions) contribute no path,
    mirroring the ``+++ /dev/null`` exclusion for text deletions. The
    resolved path passes through :func:`_sanitize_diff_path`.

    Path-with-spaces caveat: git does NOT quote plain spaces in the
    ``diff --git a/<x> b/<y>`` header, so for a binary deletion or rename
    that header is genuinely ambiguous to whitespace-split. The header is,
    however, unambiguous for the overwhelmingly-common NON-RENAME case
    (a == b: the same file edited in place), where the remainder after the
    ``diff --git `` prefix has the shape ``a/P b/P`` with both halves equal —
    :func:`_recover_inplace_header_path` recovers the full spaced ``P`` from
    it. A header that does NOT match the equal-halves shape (a genuine rename
    whose path contains a space, or an otherwise un-disambiguatable header)
    falls through to a best-effort whitespace split — renames of
    space-bearing binaries are vanishingly rare, and the default scope-gate
    mode is advisory (WARN), so a mis-recovered rename path is at worst a
    spurious advisory, never a crash.
    """
    header = section[0]
    # 1. ``Binary files a/<x> and b/<y> differ`` — the b-side after " and ".
    #    This line IS unambiguous even with spaces: the literal " and "
    #    separates the two sides regardless of spaces inside either path.
    for line in section:
        if line.startswith("Binary files ") and line.rstrip().endswith(
            " differ"
        ):
            body = line[len("Binary files "):].rstrip()
            body = body[: -len(" differ")]
            # Split on the literal " and " separating the a/ and b/ sides.
            if " and " in body:
                b_side = body.rsplit(" and ", 1)[1].strip()
                if b_side == "/dev/null":
                    return None
                if b_side.startswith("b/"):
                    b_side = b_side[len("b/"):]
                return _sanitize_diff_path(b_side)
            break
    # 2. ``diff --git a/<x> b/<y>`` header. Try the unambiguous non-rename
    #    (a == b) recovery first so paths with spaces survive intact; only
    #    fall back to the best-effort whitespace split when the header is
    #    not of the equal-halves shape (e.g. a rename with spaces).
    if header.startswith("diff --git "):
        remainder = header[len("diff --git "):].rstrip()
        b_path = _recover_inplace_header_path(remainder)
        if b_path is not None:
            if b_path == "dev/null" or b_path == "/dev/null":
                return None
            return _sanitize_diff_path(b_path)
    parts = header.strip().split()
    if len(parts) >= 4:
        b_token = parts[3]
        if b_token.startswith("b/"):
            b_token = b_token[len("b/"):]
        if b_token == "dev/null" or b_token == "/dev/null":
            return None
        return _sanitize_diff_path(b_token)
    return None


def _recover_inplace_header_path(remainder: str) -> str | None:
    """Recover the b-side path from an in-place ``diff --git`` header.

    ``remainder`` is the text after the ``diff --git `` prefix, i.e.
    ``a/<x> b/<y>``. Git leaves plain spaces UNQUOTED here, so the header is
    ambiguous to a whitespace split when a path contains a space. This helper
    handles only the unambiguous NON-RENAME case where ``x == y`` (the same
    file edited in place): the remainder then has the exact shape
    ``a/P b/P`` with ``len(remainder) == len("a/") + len(P) + len(" b/") +
    len(P)``. We compute ``P`` from that length and verify the remainder
    reconstructs to ``a/{P} b/{P}`` before returning it (the b-side, stripped
    of its ``b/`` prefix). Returns ``None`` for anything that is not an
    equal-halves in-place header (a rename with differing sides, or a
    malformed remainder), leaving the caller to fall back to its best-effort
    whitespace split. The recovered path is NOT sanitised here — the caller
    owns the ``/dev/null`` skip and :func:`_sanitize_diff_path` pass.
    """
    if not remainder.startswith("a/"):
        return None
    # len(remainder) = len("a/") + len(P) + len(" b/") + len(P)
    #               = 2 + len(P) + 3 + len(P) = 5 + 2*len(P)
    fixed = len("a/") + len(" b/")  # == 5
    inner = len(remainder) - fixed
    if inner <= 0 or inner % 2 != 0:
        return None
    p_len = inner // 2
    candidate = remainder[len("a/"): len("a/") + p_len]
    # Verify the remainder is exactly ``a/{candidate} b/{candidate}``. This
    # rejects renames (a != b) and any header that does not fit the shape.
    if remainder == f"a/{candidate} b/{candidate}":
        return candidate
    return None


def extract_files_from_diff(diff: str, *, strict: bool = False) -> list[str]:
    """Pull file paths from a unified diff (lightweight, deterministic).

    Parses the ``+++ b/<path>`` lines from a unified diff, returning paths
    in first-seen order with duplicates removed. ``+++ /dev/null`` (file
    deletion target) is naturally excluded because the prefix doesn't match.

    Lifted from ``orchestrator.phase_review_runner`` in v0.13.0 for reuse
    by the secretscan diff-scope path. The phase-review wrapper continues
    to import this function under the legacy private name to keep its
    callers stable.

    v0.27.0 (audit §6): adds a ``strict`` mode. With ``strict=False`` (the
    default — preserves v0.26.2 behaviour for legacy phase-review callers)
    a non-empty diff with no parseable ``+++ b/`` headers returns ``[]``
    silently. With ``strict=True`` the same condition raises
    :class:`errors.DiffParseError` so the QA-gate site can fail-closed on
    tasks declared as ``produces_diff=True`` rather than silently passing
    every diff-scoped gate with ``paths=[]``.

    F-4: the parse is SECTION-AWARE with ``+++ b/`` PRECEDENCE. The diff is
    split on ``diff --git `` headers (the same split
    :func:`filter_generated_from_diff` uses). For each section: if it has a
    ``+++ b/<path>`` line, THAT path is used (existing sanitisation +
    ``/dev/null`` skip intact). ONLY when a section has NO ``+++ b/`` (a
    genuinely-binary section — ``GIT binary patch`` payload or
    ``Binary files .. differ``) does it fall back to the b-side path from
    the ``diff --git`` header / ``Binary files .. differ`` line (same
    sanitisation). Precedence matters: a section pairing a clean header with
    a deliberately-malformed ``+++ b/`` line must use the malformed line (it
    is rejected by the sanitiser → contributes nothing) and must NOT parse
    the header as a fallback — so every text-diff result stays
    byte-identical and binary coverage is purely additive.

    Args:
        diff: Unified diff text. May be empty.
        strict: When ``True``, raise :class:`errors.DiffParseError` if the
            diff text is non-empty but no path (text OR binary) is
            parseable.

    Returns:
        Repo-relative paths for each file the diff modifies. Empty list
        when the diff is empty. With ``strict=False``, also empty when
        the diff contains no parseable headers.
    """
    if not diff:
        return []
    files: list[str] = []
    seen: set[str] = set()

    def _add(path: str | None) -> None:
        if path and path not in seen:
            files.append(path)
            seen.add(path)

    # Split into per-file sections keyed on the ``diff --git`` header so a
    # binary section (no ``+++ b/``) can fall back to its header b-side
    # WITHOUT ever overriding a section that does carry a ``+++ b/`` line.
    # Lines before the first ``diff --git`` (rare; a bare ``+++ b/`` diff
    # with no header — e.g. the legacy phase-review dedupe fixtures) collect
    # into a single header-less "preamble" section so their ``+++ b/`` lines
    # are still parsed exactly as before. A preamble section never triggers
    # the binary header fallback (its first line is not a ``diff --git``
    # header), so a bare ``+++ b/`` diff behaves byte-identically.
    sections: list[list[str]] = []
    current: list[str] = []  # accumulates the header-less preamble first
    for line in diff.splitlines():
        if line.startswith("diff --git "):
            if current:
                sections.append(current)
            current = [line]
        else:
            current.append(line)
    if current:
        sections.append(current)

    for section in sections:
        # ``+++ b/`` PRECEDENCE: if the section declares any ``+++ b/`` line,
        # those are authoritative for this section (binary fallback skipped).
        has_plus_b = False
        for line in section:
            if line.startswith("+++ b/"):
                has_plus_b = True
                _add(_sanitize_diff_path(line[len("+++ b/"):]))
        if has_plus_b:
            continue
        # No ``+++ b/`` in this section. The binary header fallback fires
        # ONLY for a real ``diff --git`` header (preamble sections do not
        # qualify) AND only when the section carries a positive binary
        # marker. A header-only section with NO marker is a truncated /
        # hallucinated text diff: it contributes nothing, preserving the
        # v0.27 fail-closed QA-gate contract (``strict`` then raises).
        if (
            section
            and section[0].startswith("diff --git ")
            and _section_is_binary(section)
        ):
            _add(_binary_section_target(section))

    if not files and strict:
        from errors import DiffParseError

        raise DiffParseError(
            f"diff has {len(diff)} chars but no parseable '+++ b/' headers "
            f"(first 80 chars: {diff[:80]!r})"
        )
    return files


def _git_rev_parse_head(cwd: Path) -> str | None:
    """Return the current ``HEAD`` SHA, or ``None`` when not in a repo.

    Used at phase entry to record :attr:`Phase.baseline_commit` and again
    at phase completion to capture the tip commit for the phase-review
    diff. ``None`` is returned for the same scenarios as :func:`_git_diff`
    (no ``.git`` dir, subprocess failure, non-zero exit) so callers can
    skip phase review without raising.
    """
    try:
        cwd_path = Path(cwd)
    except TypeError:
        return None
    if not (cwd_path / ".git").exists():
        return None
    try:
        import subprocess

        out = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=str(cwd_path),
            capture_output=True,
            text=True,
            errors="replace",
            timeout=5,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if out.returncode != 0:
        return None
    sha = out.stdout.strip()
    return sha or None
